version: "3"

tasks:
  deploy:
    vars:
      HOSTNAME:
        sh: hostname -s
    cmds:
      - |
        if [ {{.HOSTNAME}} -eq 'mami0tsu' ]; then
          ln -sfnv $(pwd)/gitconfig $HOME/.gitconfig
        fi

  clean:
    cmds:
      - unlink $HOME/.gitconfig
