version: "3"

tasks:
  deploy:
    vars:
      HOSTNAME:
        sh: hostname -s
    cmds:
      - ln -sfnv $(pwd)/gitconfig.{{.HOSTNAME}} $HOME/.gitconfig

  clean:
    cmds:
      - unlink $HOME/.gitconfig
