add_newline = true
scan_timeout = 10

[cmd_duration]
show_milliseconds = true

[character]
success_symbol = "[>](bole green)"
error_symbol = "[>](bold red)"
format = '$symbol'

[username]
style_user = "bold green"
style_root = "bold red"
format = '[\[](bold white)[$user]($style)[\]](bold white)'
show_always = true

[directory]
truncation_length = 100 
format = '[-\[](bold white)[$path]($style)[\]](bold white)'
