version: '3'

includes:
  agent-plugins: ./taskfiles/agent-plugins.yaml
  agent-skills: ./taskfiles/agent-skills.yaml
  nix: ./taskfiles/nix.yaml
  renovate: ./taskfiles/renovate.yaml

env:
  REPO_ROOT: '{{.ROOT_DIR}}'
  SHELL: bash

set:
  - errexit
  - nounset
  - pipefail

tasks:
  clean:
    desc: Clean Nix generations, agent plugins, and agent skills.
    cmds:
      - task: nix:clean
      - task: agent-plugins:clean
      - task: agent-skills:clean

  default:
    silent: true
    cmds:
      - task --list

  deploy:
    desc: Deploy Nix configuration, agent plugins, and agent skills.
    cmds:
      - task: nix:deploy
      - task: agent-plugins:deploy
      - task: agent-skills:deploy
