version: '3'

vars:
  nix_target: '{{.TARGET | default (env "USER")}}'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  deploy:
    desc: Deploy dotfiles using nix-darwin.
    cmds:
      - sudo darwin-rebuild switch --flake .#{{.nix_target}}

  clean:
    desc: Cleanup old Nix generations.
    cmds:
      - nix-collect-garbage -d
      - echo "Cleaned up old Nix generations. To fully free space, run with sudo."
