version: '3'

tasks:
  deploy:
    vars:
      config_dir: $HOME/.config
      target_dir: zellij,zsh,nvim,ghostty,wezterm,starship,mise,sheldon
      hostname:
        sh: hostname -s
    cmds:
      - for: { var: target_dir, split: ','}
        cmd: ln -svi $(pwd)/{{.ITEM}} {{.config_dir}}
      - ln -svi $(pwd)/zsh/.zshrc $HOME/.zshrc
      - ln -svi $(pwd)/tmux/.tmux.conf $HOME/.tmux.conf
      - |
        if [ {{.hostname}} -eq 'mami0tsu' ]; then
          ln -svi $(pwd)/git/.gitconfig $HOME/.gitconfig
        fi
      - |
        ln -svi $(pwd)/brew/.brewfile $HOME/.brewfile
        brew bundle --file=$HOME/.brewfile

  clean:
    vars:
      config_dir: $HOME/.config
      target_dir: zellij,zsh,nvim,ghostty,wezterm,starship,mise,sheldon
      target_file: .tmux.conf,.gitconfig,.zshrc,.brewfile
    cmds:
      - for: { var: target_dir, split: ',' }
        cmd: unlink {{.config_dir}}/{{.ITEM}}
      - for: { var: target_file, split: ',' }
        cmd: unlink $HOME/{{.ITEM}}
