version: '3'

vars:
  config_dir: $HOME/.config
  target_dir: ghostty mise nvim sheldon starship tmux wezterm zellij zsh

tasks:
  clean:
    desc: Clean dotfiles.
    vars:
      target_file: .brewfile .zshenv
    cmds:
      - for: { var: target_file }
        cmd: unlink $HOME/{{.ITEM}}
      - for: { var: target_dir }
        cmd: unlink {{.config_dir}}/{{.ITEM}}
      - unlink {{.config_dir}}/zsh

  default:
    silent: true
    cmds:
      - task --list

  deploy:
    desc: Deploy dotfiles.
    cmds:
      - for: { var: target_dir }
        cmd: ln -svi $(pwd)/{{.ITEM}} {{.config_dir}}
      - task: internal:deploy:brew
      - task: internal:deploy:git
      - ln -svi $(pwd)/zsh/.zshenv $HOME/.zshenv

  internal:deploy:brew:
    internal: true
    cmds:
      - ln -svi $(pwd)/brew/.brewfile $HOME/.brewfile
      - brew bundle --file=$HOME/.brewfile

  internal:deploy:git:
    internal: true
    cmds:
      - ln -svi $(pwd)/git $HOME/.config
    preconditions:
      - sh: '[ $(hostname -s) = "mami0tsu" ]'
        msg: "Hostname doesn't equal mami0tsu"
