[tools]
awscli = ['2.13.9']
"cargo:bat" = ['0.24.0']
"cargo:eza" = ['0.17.1']
"cargo:git-delta" = ['0.16.5']
"cargo:sheldon" = ['0.7.4']
"cargo:zellij" = ['0.40.1']
deno = ['1.44.4']
github-cli = ['2.32.1']
go = "1.23.1"
gojq = ['0.12.13']
jq = ['1.6']
neovim = ['0.9.4']
node = ['21.5.0']
python = ['3.12.1']
ripgrep = ['13.0.0']
rust = ['1.76.0']
starship = ['1.16.0']
terraform-ls = ['0.31.4']
tree-sitter = ['0.20.8']

[settings]
experimental = true
