[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter', 'CursorHold']
hook_source = '''
  call ddc#custom#patch_global('sources',
    \ ['around', 'file', 'rg'],
    \ )
  call ddc#custom#patch_global('sourceOptions', #{
    \   _: #{
    \     ignoreCase: v:true,
    \     matchers: ['matcher_head', 'matcher_length'],
    \     sorters: ['sorter_rank'],
    \     converters: [
    \       'converter_remove_overlap', 'converter_truncate_abbr',
    \     ],
    \   },
    \   around: #{
    \     mark: 'A',
    \   },
    \   nvim-lsp: #{
    \     mark: 'lsp',
    \     forceCompletionPattern: '\.\w*|:\w*|->\w*',
    \     dup: 'force,'
    \   },
    \ })

  if has('nvim')
    call ddc#custom#patch_filetype(
      \ ['go', 'terraform'], 'sources',
      \ ['around', 'nvim-lsp']
      \ )
  endif

  call ddc#custom#patch_global('autoCompleteEvents', [
      \ 'InsertEnter', 'TextChangedI', 'TextChangedP',
      \ 'CmdlineEnter', 'CmdlineChanged', 'TextChangedT',
      \ ])
  call ddc#custom#patch_global('ui', 'pum')

  inoremap <expr> <TAB>
        \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
        \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
        \ '<TAB>' : ddc#map#manual_complete()
  inoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
  inoremap <C-n>   <Cmd>call pum#map#select_relative(+1)<CR>
  inoremap <C-p>   <Cmd>call pum#map#select_relative(-1)<CR>
  inoremap <expr> j
        \ pum#entered() ?
        \ '<Cmd>call pum#map#insert_relative(+1)<CR>' : 'j'
  inoremap <expr> k
        \ pum#entered() ?
        \ '<Cmd>call pum#map#insert_relative(-1)<CR>' : 'k'

  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-rg'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_truncate_abbr'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = '''
  call pum#set_option(#{
    \   auto_confirm_time: 1500,
    \   max_width: 80,
    \   use_setline: v:true,
    \ })
'''

# [[plugins]]
# repo = 'matsui54/denops-popup-preview.vim'
# on_source = ['ddc.vim']
# hook_source = '''
#   call popup_preview#enable()
# '''
