[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_source = '''
  call ddu#custom#patch_global({
      \   'ui': 'filer',
      \   'sources': [
      \     {
      \       'name': 'file',
      \       'params': {},
      \     },
      \   ],
      \   'sourceOptions': {
      \     '_': {
      \       'columns': ['icon_filename'],
      \     },
      \   },
      \   'kindOptions': {
      \     'file': {
      \       'defaultAction': 'open',
      \     },
      \   },
      \   'uiParams': {
      \     'filer': {
      \       'split': 'floating',
      \     }
      \   },
      \ })
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

# [[plugins]]
# repo = 'Shougo/ddu-column-filename'
# on_source = 'ddu.vim'

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
  nnoremap <buffer> <CR>
    \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer> q
    \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
  inoremap <buffer> <CR>
    \ <Esc><Cmd>call ddu#ui#ff#close()<CR>
  nnoremap <buffer> <CR>
    \ <Cmd>call ddu#ui#ff#close()<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hook_add = '''
  nnoremap <Space>f <Cmd>Ddu
    \ -name=filer-`win_getid()` -ui=filer -resume -sync file
    \ -source-option-path=`getcwd()`
    \ -source-option-columns=icon_filename<CR>
'''
[plugins.ftplugin]
ddu-filer = '''
  nnoremap <buffer><silent> <Space>
    \ <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> *
    \ <Cmd>call ddu#ui#filer#do_action('toggleAllItems')<CR>
  nnoremap <buffer><silent> <Space>f
    \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
  nnoremap <buffer><silent> q
    \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
  nnoremap <buffer> o
    \ <Cmd>call ddu#ui#filer#do_action('expandItem',
    \ {'mode': 'toggle'})<CR>
  nnoremap <buffer> h
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'narrow', 'params': {'path': ".."}})<CR>
  nnoremap <buffer><expr> l
    \ ddu#ui#filer#is_directory() ?
    \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow'})<CR>" :
    \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"
  nnoremap <buffer> c
    \ <Cmd>call ddu#ui#filer#multi_actions([
    \ ['itemAction', {'name': 'copy'}],
    \ ['clearSelectAllItems'],
    \ ])<CR>
  nnoremap <buffer> d
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'delete'})<CR>
  nnoremap <buffer> D
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'trash'})<CR>
  nnoremap <buffer> m
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'move'})<CR>
  nnoremap <buffer> r
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'rename'})<CR>
  nnoremap <buffer> p
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'paste'})<CR>
  nnoremap <buffer> K
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'newDirectory'})<CR>
  nnoremap <buffer> N
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'newFile'})<CR>
  nnoremap <buffer> ~
    \ <Cmd>call ddu#ui#filer#do_action('itemAction',
    \ {'name': 'narrow', 'params': {'path': expand('~')}})<CR>
  nnoremap <buffer> >
    \ <Cmd>call ddu#ui#filer#do_action('updateOptions', {
    \   'sourceOptions': {
    \     'file': {
    \       'matchers': ToggleHidden('file'),
    \     },
    \   },
    \ })<CR>

  function! ToggleHidden(name)
    let current = ddu#custom#get_current(b:ddu_ui_name)
    let source_options = get(current, 'sourceOptions', {})
    let source_options_name = get(source_options, a:name, {})
    let matchers = get(source_options_name, 'matchers', [])
    return empty(matchers) ? ['matcher_hidden'] : []
  endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
