[[plugins]]
repo = 'catppuccin/nvim'
on_lua = 'catppuccin'
lua_add = '''
  require('catppuccin').setup({
    flavor = 'mocha',
    color_overrides = {
      mocha = {
        base = '#000000',
        mantle = '#000000',
        crust = '#000000',
      },
    },
    term_colors = true,
    integrations = {
      gitsigns = true,
      markdown = true,
      mason = true,
      notify = true,
      treesitter = true,
    },
  })

  vim.cmd.colorscheme 'catppuccin'
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_lua = 'lualine'
lua_add = '''
  local function diff_source()
    local gitsigns = vim.b.gitsigns_status_dict
    if gitsigns then
      return {
        added = gitsigns.added,
        modified = gitsigns.changed,
        removed = gitsigns.removed
      }
    end
  end

  require('lualine').setup({
    options = {
      icons_enabled = true,
      theme = 'auto',
      component_separators = {left = '|', right = '|'},
      section_separators = {left = '', right = ''},
      disabled_filetypes = {statusline = {}, winbar = {}},
      ignore_focus = {},
      always_divide_middle = true,
      globalstatus = true,
      refresh = {statusline = 1000, tabline = 1000, winbar = 1000}
    },
    sections = {
      lualine_a = {'mode'},
      lualine_b = {
        'branch',
        {'diff', source = diff_source},
        'diagnostics'
      },
      lualine_c = {{'filename', path = 3}},
      lualine_x = {'encoding', 'fileformat', 'filetype'},
      lualine_y = {'progress'},
      lualine_z = {'location'}
    },
    inactive_sections = {
      lualine_a = {},
      lualine_b = {},
      lualine_c = {'filename'},
      lualine_x = {'location'},
      lualine_y = {},
      lualine_z = {}
    },
    tabline = {
      lualine_a = {'buffers'},
    },
    winbar = {},
    inactive_winbar = {},
    extensions = {}
  })
'''

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
