[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_ft = ['go', 'terraform']
if = 'has("nvim")'
depends = 'ddc.vim'
lua_source = '''
  require'lspconfig'.gopls.setup{}
  require'lspconfig'.terraformls.setup{}
  --require'lspconfig'.vimls.setup{}
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
lua_source = '''
  require'nvim-treesitter.configs'.setup {
      ensure_installed = 'all',
      highlight = {
          enable = true,
      },
  }
'''
