[[plugins]]
repo = 'catppuccin/nvim'
on_lua = 'catppuccin'
lua_add = '''
  require('catppuccin').setup({
    flavor = 'mocha',
    color_overrides = {
      mocha = {
        base = '#000000',
        mantle = '#000000',
        crust = '#000000',
      },
    },
    term_colors = true,
    integrations = {
      gitsigns = true,
      markdown = true,
      mason = true,
      notify = true,
      treesitter = true,
    },
  })

  vim.cmd.colorscheme 'catppuccin'
'''
