shell = 'zsh'

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.git-open]
github = 'paulirish/git-open'
apply = ['defer']

[plugins.zsh-compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.sync]
local = '~/.config/zsh/sync'
use = ['*.zsh']

[plugins.defer]
local = '~/.config/zsh/defer'
use = ['*.zsh']
apply = ['defer']
