[tools]
awscli = ['2.13.9']
'cargo:eza' = ['0.17.1']
'cargo:sheldon' = ['0.7.4']
'cargo:bat' = ['0.24.0']
deno = ['1.37.1']
github-cli = ['2.32.1']
go = ['1.21.0']
gojq = ['0.12.13']
jq = ['1.6']
neovim = ['0.9.1']
node = ['21.5.0']
python = ['3.12.1']
ripgrep = ['13.0.0']
rust = ['1.75.0']
starship = ['1.16.0']
terraform = ['1.6.2']
terraform-ls = ['0.31.4']
tree-sitter = ['0.20.8']
"cargo:git-delta" = "latest"

[settings]
experimental = true
