[tools]
awscli = ['2.13.9']
deno = ['1.36.1']
github-cli = ['2.32.1']
go = ['1.21.0']
gojq = ['0.12.13']
jq = ['1.6']
neovim = ['0.9.1']
starship = ['1.16.0']
terraform = ['1.5.5']
terraform-ls = ['0.31.4']
tree-sitter = ['0.20.8']
