version: "3"

vars:
  CONFIG_DIR: $HOME/.config

tasks:
  deploy:
    cmds:
      - mkdir -p {{.CONFIG_DIR}}/zsh
      - ln -sfnv $(pwd)/.zshrc $HOME
      - ln -sfnv $(pwd)/sync {{.CONFIG_DIR}}/zsh
      - ln -sfnv $(pwd)/defer {{.CONFIG_DIR}}/zsh

  clean:
    cmds:
      - unlink $HOME/.zshrc
      - rm -rf {{.CONFIG_DIR}}/zsh
