---
name: Nix Config Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/nix-config-test.yaml
      - flake.lock
      - flake.nix
      - nix/**
  push:
    branches: [main]
    paths:
      - .github/workflows/nix-config-test.yaml
      - flake.lock
      - flake.nix
      - nix/**

# ワークフローレベルではパーミッションを設定しない
permissions: {}

# デフォルトシェルでパイプエラーを有効化する
defaults:
  run:
    shell: bash

# ワークフローが同じブランチで複数起動したらキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Check Nix Flake
        run: nix flake check --no-build --no-update-lock-file

      - name: Build Nix Package for CI
        run: nix build --no-link --print-build-logs .#darwinConfigurations.ci.system
