name: Shell Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.sh'
      - .github/workflows/shell-lint.yaml
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - .github/workflows/shell-lint.yaml

# ワークフローレベルではパーミッションを設定しない
permissions: {}

# デフォルトシェルでパイプエラーを有効化する
defaults:
  run:
    shell: bash

# ワークフローが同じブランチで複数起動したらキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@0722bbdb0d47f04c1b53b8734d2422ac63a45ec6 # v1.32
        with:
          fail_level: error
          filter_mode: nofilter
          path: .
          pattern: '*.sh'
          reporter: github-check
