---
name: Workflow Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/**/*.y{a,}ml
      - .github/**/action.y{a,}ml
  push:
    branches: [main]
    paths:
      - .github/workflows/**/*.y{a,}ml
      - .github/**/action.y{a,}ml

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Lint workflows with actionlint
        uses: reviewdog/action-actionlint@a499b807aed4af40b8f2f7b885b9e38c469a945c # v1.73.0
        with:
          actionlint_flags: .github/workflows/*.yaml
          fail_level: error

      - name: Audit workflows with zizmor
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          inputs: .github
          online-audits: false
          min-severity: low
          version: 1.27.0
          advanced-security: false
